[package]
name = "pf8-android"
version = "0.1.1"
edition = "2024"

[dependencies]
# pf8 = { path = "../../pfs_rs/pf8" }
pf8 = "0.1.4"
jni = "0.21.1"

[lib]
crate-type = ["cdylib"]
name = "pf8"  # 生成 libpf8.so
